import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)
GPIO.setup(3,GPIO.OUT)
GPIO.setup(5,GPIO.OUT)
GPIO.setup(7,GPIO.OUT)
GPIO.setup(11,GPIO.OUT)
GPIO.setup(13,GPIO.OUT)
GPIO.setup(15,GPIO.OUT)
GPIO.setup(19,GPIO.OUT)
GPIO.setup(21,GPIO.OUT)
def forward():
    GPIO.output(3,0)
    GPIO.output(5,1)
    GPIO.output(7,0)
    GPIO.output(11,1)
    GPIO.output(13,1)
    GPIO.output(15,0)
    GPIO.output(19,1)
    GPIO.output(21,0)
    time.sleep(2)
def backward():
    GPIO.output(3,1)
    GPIO.output(5,0)
    GPIO.output(7,1)
    GPIO.output(11,0)
    GPIO.output(13,0)
    GPIO.output(15,1)
    GPIO.output(19,0)
    GPIO.output(21,1)
    time.sleep(2)
def right():
    GPIO.output(3,0)
    GPIO.output(5,0)
    GPIO.output(7,0)
    GPIO.output(11,0)
    GPIO.output(13,1)
    GPIO.output(15,0)
    GPIO.output(19,1)
    GPIO.output(21,0)
    time.sleep(2)
def left():
    GPIO.output(3,0)
    GPIO.output(5,1)
    GPIO.output(7,0)
    GPIO.output(11,1)
    GPIO.output(13,0)
    GPIO.output(15,0)
    GPIO.output(19,0)
    GPIO.output(21,0)
    time.sleep(2)
def stop():
    GPIO.output(3,0)
    GPIO.output(5,0)
    GPIO.output(7,0)
    GPIO.output(11,0)
    GPIO.output(13,0)
    GPIO.output(15,0)
    GPIO.output(19,0)
    GPIO.output(21,0)
    time.sleep(2)
        
GPIO.cleanup()
